#!/bin/sh
set -e

# If /dev/log is either a named pipe or it was placed there accidentally,
# e.g. because of the issue documented at https://github.com/phusion/baseimage-docker/pull/25,
# then we remove it.
if [ ! -S /dev/log ]; then rm -f /dev/log; fi

RSYSLOGNG_OPTS="-x"
PID=/var/run/rsyslog.pid

[ -r /etc/default/rsyslog ] && . /etc/default/rsyslog

case "x$CONSOLE_LOG_LEVEL" in
  x[1-8])
    dmesg -n $CONSOLE_LOG_LEVEL
    ;;
  x)
    ;;
  *)
    echo "CONSOLE_LOG_LEVEL is of unaccepted value."
    ;;
esac

if [ ! -e /dev/xconsole ]
then
  mknod -m 640 /dev/xconsole p
  chown root:adm /dev/xconsole
  [ -x /sbin/restorecon ] && /sbin/restorecon $XCONSOLE
fi

if [ -f $PID ]
then
        rm -f $PID
fi

exec rsyslogd -n -i $PID $RSYSLOGNG_OPTS
